// function Card(name, atk, def, ){
//     this.name = name;
//     this.atk = atk;
//     this.def = def;

// }
// function Game(player_one, player_two){
//     this.players = [new Player, new Player],
//     this.match = 1;
//     this.round = 1;
//     this.wave = [1,2,3];
    
// }
// Game.prototype ={
//     do: function(){}
// }
// function Player(){
//     this.hand = [];
//     this.deck = [];
//     this.table = [];
//     this.draw = [];
//     function getCard(){}
//     function hireHero(){}
//     function attack(){}
//     function makeSpell(){}
//     function callLeaderSpecial(){}
//     function callHeroOrder(){}
//     function removeBody(){}
//     function moveHero(){}
//     function swapHeroes(){}
//     function passWave(){}
// }

// const CursedKnight_vanguard = () => {};
// const cardAction = (initiator, target) => {};
const Cards = [
    {
        num: 1,
        name: 'Cursed Knight',
        img: 'img-1-1_01',
        atk: 3,
        def: 6,
        vanguard: 'Intercept. When this hero takes damage form an attack, he deals the same amount to the attacker.',
        // vanguard_f = () => { var passive = ''},
        flank: 'When this hero takes damage, assign the same amount of damage to any other hero of your choice.',
        rear: 'When this unit is attacked in melee, the attacking hero or leader takes 2 damage.',
        special: 'Keep this order in play for the rest of the round. At the end of the round, discard this card and defeat any hero.',
        leader: 'Baenvier Marlgrove',
        leader_s: 'Anathematic Antagonists',
        leader_atk: 4,
        leader_def: 23,
        leader_special: 'At the end of each round, place a Curse Counter on this leader. Once per wave as a free action, you can discard a Curse Counter to give heroes you control +2 Attack Strength and to skip casuality checks for that wave.',
    },
    {
        num: 2,
        name: 'Diabolist',
        img: 'img-1-1_02',
        atk: 1,
        def: 3,
        vanguard: 'Heroes attacking this unit in melee have -3 Attack Strength.',
        flank: 'Attack: Clear a corpse. If you did, apply 3 damage to any hero.',
        rear: 'Attack: Choose a card at random from opponen`s hand. Place it face-down as a corpse in his unit.',
        special: 'Clear all corpses in your unit. For each corpse cleared this way, one hero has +1 Attack Strength this wave.',
        leader: 'Sera Malephaise',
        leader_s: 'Malevolent Morticians',
        leader_atk: 4,
        leader_def: 22,
        leader_special: 'Opposing heroes have -1 attack strength for each corpse in their unit. You heroes have +1 Attack Strength for each corpse in ther wave of your unit.',
    },
    {
        num: 3,
        name: 'Divinity',
        img: 'img-1-1_03',
        atk: 2,
        def: 4,
        vanguard: 'Attack: Remove 4 damage from a hero.',
        flank: 'Ranged Attack. When this hero deals damage, remove that much damage from another hero.',
        rear: 'Ranged Attack. Check casualties for the target of this hero`s attack immediately.',
        special: 'Each player restores all corpses to life. A player who restored fewer draws cards equal to the difference.',
        leader: 'Saint Mikhail Isen',
        leader_s: 'Ride of the Valkyries',
        leader_atk: 4,
        leader_def: 19,
        leader_special: 'At the end of each complete round, you may restore a corpse in your unit to full life.',
    },
    {
        num: 4,
        name: 'Druid',
        img: 'img-1-1_04',
        atk: 2,
        def: 5,
        vanguard: 'Intercept. Casualties are not checked for this hero until the end of a round.',
        flank: 'You do not check for casualties at the end of Vanguard waves.',
        rear: 'Attack: Return a defeated hero to life with lethal damage on it. Do not check casualties for it this wave.',
        special: 'Keep this card in play for the rest of the round. Casualties are not checked for your heroes at the end of waves.',
        leader: 'Pendros Schalla',
        leader_s: 'The Dauntless Druids',
        leader_atk: 4,
        leader_def: 22,
        leader_special: 'Orient your hero cards however you like when they come in play. The orientation alters the hero`s abilities, ignoring actual position in your unit, Normal: Vanguard; Sideways: Flank; Upside-down: Rear.',
    },
    {
        num: 5,
        name: 'Chronicler',
        img: 'img-1-1_05',
        atk: 1,
        def: 4,
        vanguard: 'Attack: Move all damage from this hero to any other hero of your choice.',
        flank: 'Attack: Choose two heroes in you unit, and transfer any amount of damage between them.',
        rear: 'Attack: Move 1 damage from your leader to this hero and move 1 damage from your leader to an opposing leader.',
        special: 'Move up to 4 damage from your leader to a hero.',
        leader: 'Dravil Coldwater',
        leader_s: 'Tides of Battle',
        leader_atk: 4,
        leader_def: 15,
        leader_special: 'At the end of each wave, you may move one damage from any hero or leader to any other hero or leader.',
    },
    {
        num: 6,
        name: 'Immortal',
        img: 'img-1-1_06',
        atk: 3,
        def: 2,
        vanguard: 'Intercept. Damage taken by this hero from attacks is reduced to 1.',
        flank: 'You leader cannot take more than 2 damage from a single attack.',
        rear: 'Ranged Attack. +2 Attack Strength against Rear heroes.',
        special: 'Pick up all damage on a single hero and redistribute it freely to other heroes.',
        leader: 'Byron Krane',
        leader_s: 'Charge of the Lich Brigade',
        leader_atk: 6,
        leader_def: 5,
        leader_special: 'Heroes in this unit have exactly 2 life. Any time damage would be applied to a hero or leader in this unit, that damage is reduced to 1.',
    },
    {
        num: 7,
        name: 'Inventor',
        img: 'img-1-1_07',
        atk: 1,
        def: 5,
        vanguard: 'Attack: Play an Order, then make a melee attack with this hero with +2 Attack Strength.',
        flank: 'Attack: Play an Order, then shuffle it back into you deck instead of discarding it.',
        rear: 'Attack: Play an Order, then each opponent must discard the same card if they have it in hand.',
        special: 'Shuffle all corpses in your unit back into your deck.',
        leader: 'Byron Krane',
        leader_s: 'Charge of the Lich Brigade',
        leader_atk: 3,
        leader_def: 18,
        leader_special: 'At the start of each round, reveal the top card of your deck and set is aside out of play. Every hero in your unit has the powers of that hero in addition to their own. Discard it at the end of the round.',
    },
    {
        num: 8,
        name: 'Lorekeeper',
        img: 'img-1-1_08',
        atk: 2,
        def: 4,
        vanguard: '+3 Attack Strength if you have 4 or more cards in hand.',
        flank: 'Attack: Look at the top 4 cards of your deck. Put them back in any order, then draw a card.',
        rear: 'Attack: Reveal the top card of each deck. For each card, you may put it back, or discard it. Draw a card.',
        special: 'You may draw up to 3 cards. Each opponent draws the same number as you, minus 1.',
        leader: 'Marmelee Greyheart',
        leader_s: 'Librarian Corps',
        leader_atk: 2,
        leader_def: 20,
        leader_special: 'At the end of each wave, if you fewer than 4 cards in hand, draw a card.',
    },
    {
        num: 9,
        name: 'Magical Knight',
        img: 'img-1-1_09',
        atk: 2,
        def: 4,
        vanguard: '+5 Attack Strength against heroes with 5 or more Attack Strength.',
        flank: 'Your leader cannot take more than 3 damage from a single attack.',
        rear: 'Ranged Attack. Forerunner has Intercept.',
        special: 'Apply 8 damage to any hero.',
        leader: 'Irialanradayamorella',
        leader_s: 'Cosmic Justice Rangers',
        leader_atk: 1,
        leader_def: 22,
        leader_special: 'Each time a hero in this unit is defeated, this leader gains +1 Attack Strength permanently, and removes 3 points of damage from itself.',
    },
    {
        num: 10,
        name: 'Puppeteer',
        img: 'img-2-2_01',
        atk: 2,
        def: 4,
        vanguard: 'Attack: Trade control and position of this hero and another hero in melee.',
        flank: 'Attack: Apply damage to a hero equal to the strength of its forerunner.',
        rear: 'Attack: Apply damage to a hero equal to the strength of its supporter.',
        special: 'Activate the Order power of a hero you control in the current wave.',
        leader: 'Tanis Trilives',
        leader_s: 'Performing Puppet Troupe',
        leader_atk: 3,
        leader_def: 14,
        leader_special: 'You can give attack actions to enemy heroes in melee as though you controlled those heroes and the were standing in your unit. These attacks do count towards the one action per turn limit.',
    },
    {
        num: 11,
        name: 'Relic Hunter',
        img: 'img-2-2_02',
        atk: 3,
        def: 7,
        vanguard: 'Intercept. Your Vanguard heroes are immune to `defeat` effects controlled by opponents.',
        flank: 'Attack: All heroes have +2 Attack Strength until the end of your next turn.',
        rear: '+5 Attack Strength',
        special: 'Reveal a card from the top of your deck. Either keep or discard it. Repeat this process until you keep one.',
        leader: 'Cesar Grist',
        leader_s: 'Reliquary Regiment',
        leader_atk: 4,
        leader_def: 24,
        leader_special: 'After each round, place a Threat Counter on this leader. All heroes and leaders in this unit have +2 Attack Strength per Threat Counter on this leader. When you Recruit or play an Order, discard all Threat Counters.',
    },
    {
        num: 12,
        name: 'Sage',
        img: 'img-2-2_03',
        atk: 0,
        def: 4,
        vanguard: 'Intercept. At the end of each wave, remove 1 damage from this hero before checking casualties.',
        flank: 'Attack: Return a hero in melee to its owner`s hand.',
        rear: 'At the end of each rear wave, apply 3 damage to each hero in melee.',
        special: 'Remove 4 damage from each hero',
        leader: 'Laxus the Shattered',
        leader_s: 'World Changers',
        leader_atk: 3,
        leader_def: 23,
        leader_special: 'Whenever a player plays an Order, he adds that card to the hand of the opponent whose turn comes next instead of discarding it. Heroes in this unit have +2 life.',
    },
    {
        num: 13,
        name: 'Plaguebearer',
        img: 'img-2-2_04',
        atk: 3,
        def: 4,
        vanguard: 'Attack: Apply 2 damage to each hero in a column in the enemy unit.',
        flank: 'Attack: Apply 2 damage to an opposing leader.',
        rear: 'Attack: Apply 2 damage to each hero in a wave in the enemy unit.',
        special: 'Apply 3 damage to any hero. Take another action.',
        leader: 'Kajia Septie Salix',
        leader_s: 'Rotten to the Corps',
        leader_atk: 4,
        leader_def: 12,
        leader_special: 'At the end of each wave, you may move 1 damage from this leader and from each of your heroes in that wave onto another hero (a;; of this damage mmust move to the same hero).',
    },
    {
        num: 14,
        name: 'Monster Hunter',
        img: 'img-2-2_05',
        atk: 3,
        def: 5,
        vanguard: 'Once per attack with this hero, you may discard one card for +3 Attack Strength.',
        flank: 'Forerunner has +4 Attack Strength against Vanguard heroes.',
        rear: 'Attack: Clear a corpse from an opponent`s unit, then dear 2 cards.',
        special: 'Clear all corpses in all units. Take an extra action.',
        leader: 'Joal Kalmor',
        leader_s: 'Dragonslayers Patrol',
        leader_atk: 2,
        leader_def: 20,
        leader_special: 'While you hand is larger than any opponent`s hand, your heroes and leader have +3 Attack Strength. While it is smaller than any opponent`s hand, your heroes and leader take 1 less damage from attacks.',
    },
    {
        num: 15,
        name: 'Mastermind',
        img: 'img-2-2_06',
        atk: 3,
        def: 6,
        vanguard: '+3 Attack Strength if an Order was played durning this wave.',
        flank: 'Attack: Reveal an Order from your hand and perform its effect. Then defeat this hero.',
        rear: 'After the first Order in a wave is played by any player, no more Orders may be played durning the wave.',
        special: 'Keep this order in play for the rest of the round. Other players cannot be play orders.',
        leader: 'Malandrax Mecchi',
        leader_s: 'Sinister Sabotage Squad',
        leader_atk: 4,
        leader_def: 20,
        leader_special: 'When any other player plays an Order, you may discard a card. If you do, cancel the order. Otherwise, you draw a card.',
    },
    {
        num: 16,
        name: 'Planebinder',
        img: 'img-2-2_07',
        atk: 2,
        def: 5,
        vanguard: 'Attack: Move a hero in melee to any empty space in its unit and do 2 damage to it.',
        flank: 'Attack: Move a hero to any empty space in its unit.',
        rear: 'Attack: Do 2 damage to all heroes in an enemy rear row.',
        special: 'Put a hero onto the top of its owner`s deck.',
        leader: 'Kaitlyn Van Sorrel',
        leader_s: 'Planar Patrollers',
        leader_atk: 2,
        leader_def: 16,
        leader_special: 'You can use Restructure actions to affect you opponent`s unit. It takes two actions to restructure enemy heroes with the Intercept ability.',
    },
    {
        num: 17,
        name: 'Operative',
        img: 'img-2-2_08',
        atk: 2,
        def: 5,
        vanguard: 'This hero cannot be targeret by an opponent`s orders or attack powers.',
        flank: 'Attack: Destroy this hero and another hero.',
        rear: 'Ranged Attack',
        special: 'Destroy a hero, then clear that hero`s corpse.',
        leader: 'Clinhyde Eight',
        leader_s: 'Power Up Platoon',
        leader_atk: 2,
        leader_def: 20,
        leader_special: 'Twice per wave, you may discard a card from your hand to take an extra action.',
    },
    {
        num: 18,
        name: 'Necromancer',
        img: 'img-2-2_09',
        atk: 2,
        def: 6,
        vanguard: '+2 Attack Strength for each corpse in your Vanguard.',
        flank: 'Leader, Forerunner, and Supporter have +2 Attack Strength.',
        rear: 'Ranged Attack. +1 Attack Strength for each corpse in your vanguard.',
        special: 'Each corpse in your unit makes a strength 3 melee attack agains a hero. Then remove those corpses.',
        leader: 'Voco Astrum',
        leader_s: 'Metal Militia',
        leader_atk: 2,
        leader_def: 21,
        leader_special: 'A corpse in your unit is considered to be a hero with 1 life and 2 attacks strength that blocks melee. When a corpse in your unit has lethal damage, it is cleared instantly.',
    },
    {
        num: 19,
        name: 'Game Designer',
        img: 'img-7-7_01',
        atk: 3,
        def: 4,
        vanguard: 'Attack strength is equal to the number of cards in the opposing discard pile.',
        flank: 'All heroes who would become corpses are discarded instead.',
        rear: 'Attack: Your opponent discards the top 3 cards of his deck.',
        special: 'Name a card that is not the opponent`s leader. Your opponent discards that card from his unit, hand, or deck.',
        leader: 'D. Brad Talton Jr.',
        leader_s: 'The Game Changers',
        leader_atk: 3,
        leader_def: 25,
        leader_special: 'At the end of each complete round of combat, name a card other than the opposing leader. Both players discard that card from their units, hand, or decks.',
    },
    {
        num: 20,
        name: 'Reporter',
        img: 'img-7-7_02',
        atk: 0,
        def: 5,
        vanguard: 'Attack: Kill a hero who is adjacent to a corpse.',
        flank: 'Draw a card each time a hero in this unit is killed.',
        rear: 'Attack: Discard a card. If you do, draw 2 cards.',
        special: 'If there are 8 corpses in your opponent`s unit, rout the opposing unit.',
        leader: 'Marion',
        leader_s: 'Retro Reconnaissance Team',
        leader_atk: 1,
        leader_def: 19,
        leader_special: 'Once per wave, as an action, you may reveal a card from your hand to instantly kill an opposing hero with the same name as the revealed card.',
    },
    {
        num: 21,
        name: 'Gameshow Host',
        img: 'img-7-7_03',
        atk: 1,
        def: 6,
        vanguard: 'Attack: Your opponent must either discard 2 cards or kill a hero in his unit.',
        flank: 'Other heroes in this unit cannot be targeted by `kill` effects.',
        rear: 'Attack: Randomly select a card from your hand and recruit it to any space in your unit.',
        special: 'Draw 10 cards, then discard down to 5 cards. You have 30 seconds to do this, or you must discard them all!',
        leader: 'Roy',
        leader_s: 'The Pixel is Right',
        leader_atk: 1,
        leader_def: 25,
        leader_special: 'After each round, name a card, then your opponent reveals his hand. If the card is in your opponent`s hand, his leader takes 4 damage.',
    },
    {
        num: 22,
        name: 'Collector',
        img: 'img-7-7_04',
        atk: 0,
        def: 5,
        vanguard: '+1 Attack Strength for each card in hand (maximum of +7)',
        flank: 'If you use a draw action and have fewer than 7 cards in hand, draw an extra card.',
        rear: 'Attack: Add a corpse from your opponent`s unit to your hand.',
        special: 'Draw all cards in your deck. At the end of the next rear wave, you lose the game.',
        leader: 'Arcus',
        leader_s: 'Gotta catch`em All',
        leader_atk: 2,
        leader_def: 20,
        leader_special: 'At the end of each wave, if you have fewer than 7 cards, draw a card for free.',
    },
    {
        num: 23,
        name: 'Apprentice',
        img: 'img-7-7_05',
        atk: 2,
        def: 4,
        vanguard: 'Attack: Swap position and control of this hero and an opposing hero.',
        flank: 'The opponent cannot order or recruit cards that have the same name as heroes in this unit.',
        rear: 'Attack: Draw a card from your opponent`s deck.',
        special: 'Trade hands with your opponent. (Discard this order first)',
        leader: 'Verona',
        leader_s: 'Spellcasting Shuffle Squad',
        leader_atk: 1,
        leader_def: 19,
        leader_special: 'After the end of each round, you and your opponent trade hands. Then the player with fewer cards draws until he has the same number as the player with more.',
    },
    {
        num: 24,
        name: 'Game Artist',
        img: 'img-7-7_06',
        atk: 0,
        def: 6,
        vanguard: '+1 Attack Strength for each differently illustrated card in play.',
        flank: 'Attack: Use a blank index card and make a copy of another hero in play. Recruit the copy.',
        rear: 'Attack: Use a blank index card and make a copy of a card in your hand. Add it to your hand.',
        special: 'Use a blank index card and make a copy of any other Pixel Tactics card. Add it to your hand.',
        leader: 'Fabio Fontes',
        leader_s: 'The Rough Ranters',
        leader_atk: 3,
        leader_def: 26,
        leader_special: 'At the start of the game, take 3 index cards and write the names of 3 different Pixel Tactics cards. Place these in your hand. They count as copies of the named cards and have all the effects and stats of the originals.',
    },
    {
        num: 25,
        name: 'Game Reviewer',
        img: 'img-7-7_07',
        atk: 1,
        def: 5,
        vanguard: 'When this hero attacks, roll a d6. The attack has that much extra strength.',
        flank: 'Attack: Roll 2d6. If you roll 7 or greater, take 2 extra actions.',
        rear: 'Attack: Choose a hero and roll 2d6. That target`s remaining life becomes equal to the difference in the two die rolls.',
        special: 'Challenge your opponent to another 2-player game. The winner of that game can destroy and three heroes of choice.',
        leader: 'Tom Vasel',
        leader_s: 'Towering Dice Division',
        leader_atk: 5,
        leader_def: 19,
        leader_special: 'At the end of  each wave, roll 2d6. If your roll equals the number of corpse in your opponent`s unit, rout the opposing unit.',
    },
    {
        num: 26,
        name: 'Warmage',
        img: 'img-8-8_01',
        atk: 4,
        def: 3,
        vanguard: 'Attack: Do 3 damage to every opposing hero in melee.',
        flank: 'Ranged Attack',
        rear: 'Ranged Attack. +3 Attack Strength. It takes 2 actions to perform an attack with this hero.',
        special: 'Defeat a hero. Each opponent may now choose to defeat any hero. If any does, you may defeat another hero.',
        leader: 'Larimore Burman',
        leader_s: 'Dragon Buster Brigade',
        leader_atk: 4,
        leader_def: 20,
        leader_special: 'Heroes in this unit can use any their Attack Powers (those that say `Attack:`), regardless of position.',
    },
    {
        num: 27,
        name: 'Tactician',
        img: 'img-8-8_02',
        atk: 0,
        def: 4,
        vanguard: 'Intercept: This hero cannot take more than 2 damage from a single attack.',
        flank: 'All of your Vanguard Heroes have Intercept.',
        rear: 'All of your Vanguard Heroes take 2 less damage from attacks (to a minimum of 1).',
        special: 'Keep this order in play for the rest of the round. Your heroes and leaders take 2 less damage from attacks.',
        leader: 'Amon Elcela',
        leader_s: 'Kings of Denial',
        leader_atk: 0,
        leader_def: 34,
        leader_special: 'All of your heroes have the Attack Power: `Attack: Remove 4 damage from this hero and 1 damage from your leader.',
    },
    {
        num: 28,
        name: 'Supervillain',
        img: 'img-8-8_03',
        atk: 0,
        def: 3,
        vanguard: 'Attack: Draw 3 cards.',
        flank: 'Attack: Discard a card. Do damage equal to its hero Attack Strength to any hero.',
        rear: 'You may discard 2 cards at any time to cancel the effects of an order.',
        special: 'Discard any number of cards. Each opponent discards at random the same number of cards +1.',
        leader: 'Bors Vilnar',
        leader_s: 'The Shadow Government',
        leader_atk: 0,
        leader_def: 13,
        leader_special: 'This leader cannot gain or lose damage except by its own effect. Each time a hero in this unit is defeated during a casualty check, this leader takes 1 damage. At the end of a round, if this unit has no heroes, it is routed.',
    },
    {
        num: 29,
        name: 'Warlock',
        img: 'img-8-8_04',
        atk: 2,
        def: 3,
        vanguard: 'When an opposing Vanguard hero is defeated, remove all damage from any hero with non-lethal damage.',
        flank: 'Attack: Discard 2 cards to destroy a hero with no supporters or forerunners.',
        rear: 'Ranged Attack. A hero attacked by this hero cannot attack during this wave.',
        special: 'Keep this order in play for the rest of the round. Opponents cannot Recruit.',
        leader: 'Jasper Haekel',
        leader_s: 'Rasping Regiment',
        leader_atk: 5,
        leader_def: 19,
        leader_special: 'As an action, you can defeat one of your heroes to defeat an opposing hero with remaining life less than or equal to your hero`s Attack Strength.',
    },
    {
        num: 30,
        name: 'Technologist',
        img: 'img-8-8_05',
        atk: 3,
        def: 3,
        vanguard: 'Opponent`s heroes cannot Intercept Ranged Attack.',
        flank: 'Opponent`s Flank heroes cannot use Attack Powers.',
        rear: 'Opponent`s Rear heroes cannot perform Ranged Attack.',
        special: 'Keep this order in play for the rest of the round. Opponents receive 1 less action each wave.',
        leader: 'Sarafina Vanedran',
        leader_s: 'Singularity Shock Force',
        leader_atk: 5,
        leader_def: 20,
        leader_special: 'Whenever an opponent would choose a target for an order or attack power, you may choose that target insteadfrom among legal targets within the unit of his choice.',
    },
    {
        num: 31,
        name: 'Sniper',
        img: 'img-8-8_06',
        atk: 6,
        def: 3,
        vanguard: '+4 Attack Strength against heroes with Intercept.',
        flank: 'Ranged Attack. Attack: Discard 2 cards to destroy a damaged hero.',
        rear: 'Ranged Attack. Attack: An opponent discard a card at random.',
        special: 'Give a hero +2 Attack Strength and Ranged Attack during this wave.',
        leader: 'Ottavia Six',
        leader_s: '`Negotiations` Team',
        leader_atk: 7,
        leader_def: 14,
        leader_special: 'This leader`s attack is ranged. You may use two actions to discard a card from your and defeat any hero.',
    },
    {
        num: 32,
        name: 'Werewolf',
        img: 'img-8-8_07',
        atk: 3,
        def: 5,
        vanguard: 'Attack: make a melee attack, then take another action.',
        flank: 'Attack: A hero in your vanguard makes a melee attack, then take another action.',
        rear: 'Attack: Defeat this hero and another hero.',
        special: 'Draw 3 cards, discard 2 cards.',
        leader: 'Jager Brandtford',
        leader_s: 'Feral Fist Fighters',
        leader_atk: 4,
        leader_def: 18,
        leader_special: 'Making a melee attack is a free action for you. No hero or leader in your unit may attack more than once per wave.',
    }

];
  
module.exports = Cards;